# Keras API for Tensorflow

## Loading and Preprocessing the Wine Data

In [1]:
from sklearn.datasets import load_wine
wine_data = load_wine()
print(wine_data['DESCR'])

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [2]:
feature_data = wine_data['data']
labels = wine_data['target']
num_classes = 3

In [3]:
# Partitioning
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(feature_data, labels, test_size=0.3, random_state=0)

# Scaling
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)

## Modeling using Keras API

Some of the Keras API is in tf.contrib while other is in tf.keras

In [4]:
import tensorflow as tf
from tensorflow.contrib.keras import models

In [5]:
dnn_keras_model = models.Sequential()

Now sequentially add densely connected layers on top of each other

In [6]:
from tensorflow.contrib.keras import layers
# Since it is the first layer, you need to define the input dimensions
dnn_keras_model.add(layers.Dense(units=13, input_dim=13, activation='relu'))

Instructions for updating:
Colocations handled automatically by placer.


In [7]:
# Second Layer
dnn_keras_model.add(layers.Dense(units=13, activation='relu'))
# Third Layer
dnn_keras_model.add(layers.Dense(units=13, activation='relu'))
# Final Layer
# 3 Units - one for each class, with softmax
dnn_keras_model.add(layers.Dense(units=num_classes, activation='softmax'))

Compile the Model

In [8]:
from tensorflow.contrib.keras import losses, optimizers, metrics, activations
# using sparse categorical crossentropy as the y_train and y_test are not already one Hotted
dnn_keras_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

Train the model

In [9]:
dnn_keras_model.fit(scaled_X_train, y_train, epochs=50) # Optionally can perform validation split here

Epoch 1/50
124/124 [==============================] - 1s 6ms/sample - loss: 1.0709 - acc: 0.4919
Epoch 2/50
124/124 [==============================] - 0s 227us/sample - loss: 1.0602 - acc: 0.6129
Epoch 3/50
124/124 [==============================] - 0s 238us/sample - loss: 1.0514 - acc: 0.6452
Epoch 4/50
124/124 [==============================] - 0s 241us/sample - loss: 1.0417 - acc: 0.6613
Epoch 5/50
124/124 [==============================] - 0s 223us/sample - loss: 1.0309 - acc: 0.6774
Epoch 6/50
124/124 [==============================] - 0s 194us/sample - loss: 1.0212 - acc: 0.6855
Epoch 7/50
124/124 [==============================] - 0s 152us/sample - loss: 1.0119 - acc: 0.6935
Epoch 8/50
124/124 [==============================] - 0s 225us/sample - loss: 1.0033 - acc: 0.6935
Epoch 9/50
124/124 [==============================] - 0s 273us/sample - loss: 0.9951 - acc: 0.7016
Epoch 10/50
124/124 [==============================] - 0s 168us/sample - loss: 0.9868 - acc: 0.7016
Epoch 11/50

Make Predictions

In [13]:
pred = dnn_keras_model.predict(scaled_X_test)
pred[:5] # This returns the softmax values for each class

array([[0.919404  , 0.01294519, 0.06765091],
       [0.15783016, 0.06257392, 0.7795959 ],
       [0.17447695, 0.78228056, 0.0432425 ],
       [0.8450709 , 0.04435303, 0.11057606],
       [0.27304298, 0.5752478 , 0.15170923]], dtype=float32)

In [14]:
predictions = dnn_keras_model.predict_classes(scaled_X_test)
predictions[:5]

array([0, 2, 1, 0, 1])

## Evaluating the Model

In [17]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        22
           2       1.00      1.00      1.00        13

   micro avg       1.00      1.00      1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54



In [18]:
confusion_matrix(y_test, predictions)

array([[19,  0,  0],
       [ 0, 22,  0],
       [ 0,  0, 13]])